<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <PackageId>FESScript</PackageId>
    <Authors>Martin Komárek</Authors>
    <Company>FESScript</Company>
    <Product>FESScript</Product>
    <UseWindowsForms>False</UseWindowsForms>
    <AnalysisLevel>none</AnalysisLevel>
    <ApplicationIcon>FES.ico</ApplicationIcon>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile></DocumentationFile>
    <FileAlignment>512</FileAlignment>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <FileAlignment>512</FileAlignment>
    <Optimize>False</Optimize>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="FESScriptFiles\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="FESScriptFiles\**" />
    <None Remove="bin\**" />
    <None Remove="FESScriptFiles\**" />
    <Page Remove="bin\**" />
    <Page Remove="FESScriptFiles\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CodeWorks\BlockCreation\BlockRecreation.cs" />
    <Compile Remove="CodeWorks\BlockCreation\Pre3Loader.cs" />
    <Compile Remove="Graphics\UserControls\OldBlock.cs" />
    <Compile Remove="Graphics\UserControls\OldBlockType.cs" />
    <Compile Remove="Graphics\UserControls\UserControlPlus.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Graphics\Windows\Displays\SettingsDisplay.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Graphics\Windows\Displays\ContentDisplay.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Graphics\Windows\Displays\DotDisplay.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="FES.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>

</Project>
